apiVersion: process.processprovider.crossplane.io/v1alpha1
kind: Process
metadata:
  name: test-flprocess
spec:
  forProvider:
    # name: "prova"
    nodeAddress: "nodeserf.cloudmmwunibo.it"
    username: "lucaserf"
    password: "lTLm#191"
  # baremetal:
  providerConfigRef:
    name: processprovider-config
