apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: process-provider-secret
type: Opaque
data:
  # credentials: BASE64ENCODED_PROVIDER_CREDS
---
apiVersion: processprovider.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: processprovider-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: process-provider-secret
      key: credentials
